name: Test
run-name: Run Push Date Test
on: push
jobs:
  date_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run app
        run: python3 hello_app/app.py &

      - name: Test GET-request
        run: |
          chmod +x ./tests/test.sh
          ./tests/test.sh
        shell: bash
